package lexer.token;

public enum TokenType {
    BROJ, REALAN, SLOVO, TEKST, NIZ, POGODAK,
    MOJ, MOJE, ZAPOCNI_IGRU, ZAVRSI_IGRU, FUNKCIJA, AKO, I ,ILI, NE, INACE, RADI, VRATI,

    UPISI,NAPISI,
    IDENT, INT_LIT, STR_LIT, CH_LIT, BOOL_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE, SEPARATOR_COMMA, TYPE_COLON, SEMICOLON,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN,
    NEWLINE, EOF
}
